# Generated by Django 4.2.7 on 2023-12-13 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('imageURL', models.CharField(blank=True, max_length=100)),
                ('eventDate', models.CharField(max_length=100)),
                ('eventTime', models.CharField(max_length=100)),
                ('venueName', models.CharField(blank=True, max_length=100)),
                ('venueCity', models.CharField(blank=True, max_length=100)),
                ('venueState', models.CharField(blank=True, max_length=100)),
                ('venueAdd', models.CharField(blank=True, max_length=100)),
                ('eventURL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('imageURL', models.CharField(blank=True, max_length=100)),
                ('eventDate', models.CharField(max_length=100)),
                ('eventTime', models.CharField(max_length=100)),
                ('venueName', models.CharField(blank=True, max_length=100)),
                ('venueCity', models.CharField(blank=True, max_length=100)),
                ('venueState', models.CharField(blank=True, max_length=100)),
                ('venueAdd', models.CharField(blank=True, max_length=100)),
                ('eventURL', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
