# Generated by Django 4.2.7 on 2023-12-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_alter_cartevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartevent',
            name='user',
        ),
    ]
